spring.application.name=api
spring.data.mongodb.uri=mongodb://localhost:27017/Prune
server.error.include-message=always
server.error.include-exception=true
server.error.include-stacktrace=always

app-secret-key=4a616453475242514e6d5a71343536373839304142434445464748494a4b4c4d
app.expiration-time=9000000